### PR TITLE
Added validation of data types in the cookie

### PR DESCRIPTION
**Pull request by lucianopw**

### CODE REVIEW

**Comment by gildas-lormeau** [comment]
@lucianopw Out of curiosity, why did you close the PR?

**Comment by lucianopw** [comment]
I was afraid that what I did was not completely right or outside of the
standards.

Francisco Luciano


Em qui., 1 de ago. de 2024 às 10:15, Gildas ***@***.***>
escreveu:

**Comment by gildas-lormeau** [comment]
No worries on my side, I can merge your PR if you wish.

**Comment by gildas-lormeau** [comment]
Thank you for your contribution :)

**Pull request merged**
